import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className='min-h-screen flex flex-col'>
        <Header />
        <div className='flex-1'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
